timezone: Europe/Amsterdam
run_days: [MON, TUE, WED, THU, FRI, SAT, SUN]
poll_interval_seconds: 60

jobs:

    # daily calculations (raw+working+trim+focus)
  - name: bist_daily_calc
    run_days: [MON, TUE, WED, THU, FRI,SAT,SUN]
    at: "02:00"
    cmd: "venv/bin/python3 -u main_bist_daily_data.py"
    lock: "bist_daily_calc"

  - name: bist_indicators
    # run_days: [SUN] #remove if u will use depends on
    # at: "23:27" #remove if u will use depends on
    depends_on: "bist_daily_calc" #open for depends usage
    cmd: "venv/bin/python3 -u main_bist_indicators.py"
    lock: "bist_indicators"

  - name: bist_1min_batch #min data update
    # run_days: [MON, TUE, WED, THU, FRI]
    # at: "21:45"
    depends_on: "bist_indicators" #open for depends usage
    cmd: "venv/bin/python3 -u main_bist_1min_data.py"
    lock: "bist_1min_batch"

  - name: usa_1min_batch
    run_days: [MON, TUE, WED, THU, FRI, SAT, SUN]
    at: "08:00"
    cmd: "venv/bin/python3 -u main_usa_1min_data.py"
    lock: "usa_1min_batch"

  - name: usa_indicators 
    depends_on: "usa_1min_batch"  #"bist_batch" #open for depends usage
    # run_days: [SUN] #remove if u will use depends on
    # at: "23:32" #remove if u will use depends on
    cmd: "venv/bin/python3 -u main_usa_indicators.py"
    lock: "usa_indicators"

  ### backup and restore for postgresql  ####
  - name: backup_to_local_trigger
    # depends_on: "usa_batch"  #"bist_batch" #open for depends usage
    run_days: [MON, TUE, WED, THU, FRI, SAT] #remove if u will use depends on
    at: "13:30" #remove if u will use depends on
    cmd: "venv/bin/python3 -u main_backup_trigger.py"
    lock: "backup_to_local_trigger"

  - name: restore_from_backup
    depends_on: "backup_to_local_trigger"  #"backup_trigger" #open for depends usage
    # run_days: [SUN] #remove if u will use depends on
    # at: "23:32" #remove if u will use depends on
    cmd: "venv/bin/python3 -u main_local_restore_trigger.py"
    lock: "restore_from_backup"