timezone: Europe/Amsterdam
run_days: [MON, TUE, WED, THU, FRI, SAT, SUN]
poll_interval_seconds: 60

jobs:
  - name: initial_scope_clone
    run_days: [MON, TUE, WED, THU, FRI, SAT, SUN]
    at: "19:30"
    cmd: ".venv/bin/python -u initial_clone_symbol_list_all.py"
    lock: "initial_scope_clone_lock"

  - name: bist_hourly
    run_days: [MON, TUE, WED, THU, FRI]
    at: "19:33"
    cmd: ".venv/bin/python -u main_bist_hourly_data.py"
    lock: "bist_hourly_lock"

  - name: ams_hourly
    run_days: [MON, TUE, WED, THU, FRI]
    at: "20:00"
    cmd: ".venv/bin/python -u main_ams_hourly_data.py"
    lock: "ams_hourly_lock"

  - name: nasdaq_hourly
    run_days: [MON, TUE, WED, THU, FRI]
    at: "23:30"
    cmd: ".venv/bin/python -u main_nasdaq_hourly_data.py"
    lock: "nasdaq_hourly_lock"

  - name: nyse_hourly
    run_days: [MON, TUE, WED, THU, FRI]
    at: "23:55"
    cmd: ".venv/bin/python -u main_nyse_hourly_data.py"
    lock: "nyse_hourly_lock"

  - name: backup_to_local
    depends_on: "nyse_hourly" #open for depends usage
    cmd: ".venv/bin/python -u main_backup_trigger.py"
    lock: "backup_to_local_lock"

  - name: crypto_hourly
    run_days: [MON, TUE, WED, THU, FRI, SAT, SUN]
    at: "23:57"
    cmd: ".venv/bin/python -u main_crypto_hourly_data.py"
    lock: "crypto_hourly_lock"

  - name: assets_hourly
    run_days: [MON, TUE, WED, THU, FRI, SAT]
    at: "22:30"
    cmd: ".venv/bin/python -u main_assets_hourly_data.py"
    lock: "assets_hourly_lock"

  